#!/usr/bin/env sh


#
#
# By and © Francesco Munafò
#
# Apply bin2c to all .raw files
#
# allraw2c src/ dest/
#
# if in src/ there is a file called woosh.raw it will call:
#
# bin2c "srcs/woosh.raw" "dest/woosh" "woosh"
#
# (bin2c inFileName outFileNameNoExt symbolName)
# (srcs and dest are relative to the working directory)
# (a bin2c command must be available)
#
#


if [ ${#2} -eq 0 ]
then

	if [ ${#1} -eq 0 ]
	then
		find . -name "*.raw" | while read f ; do 
			fileBase=${f##*/}
			fileBaseNoExt=${fileBase%.*}
			bin2c "$f" "$fileBaseNoExt" "$fileBaseNoExt" ; 
		done
	else
		find "$1" -name "*.raw" | while read f ; do 
			fileBase=${f##*/}
			fileBaseNoExt=${fileBase%.*}
			echo "bin2c \"$f\" \"${2%/}/$fileBaseNoExt\" \"$fileBaseNoExt\"" ; 
			bin2c "$f" "$fileBaseNoExt" "$fileBaseNoExt" ; 
		done
	fi

else
	
	if [ ${#1} -eq 0 ]
	then
		find . -name "*.raw" | while read f ; do 
			fileBase=${f##*/}
			fileBaseNoExt=${fileBase%.*}
			echo "bin2c \"$f\" \"${2%/}/$fileBaseNoExt\" \"$fileBaseNoExt\"" ; 
			bin2c "$f" "${2%/}/$fileBaseNoExt" "$fileBaseNoExt" ; 
		done
	else
		find "$1" -name "*.raw" | while read f ; do 
			fileBase=${f##*/}
			fileBaseNoExt=${fileBase%.*}
			echo "bin2c \"$f\" \"${2%/}/$fileBaseNoExt\" \"$fileBaseNoExt\"" ; 
			bin2c "$f" "${2%/}/$fileBaseNoExt" "$fileBaseNoExt" ; 
		done
	fi

fi
